name: pokemonapp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

  #Navigation
  auto_route: ^7.8.3
  #State Management
  provider: ^6.0.5
  #Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #Pagination
  infinite_scroll_pagination: ^4.0.0
  #Http Client
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6


flutter:

  
  uses-material-design: true
